on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: checkout the code
        uses: actions/checkout@v5
      - name: install go
        uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: run unit tests
        run: task test
      - name: build a local artifact
        run: task build